base:
  enableCRDTemplates: true
istiod:
  pilot:
    resources:
      requests:
        cpu: 500m
        memory: 2048Mi
      limits:
        cpu: 1000m
        memory: 4096Mi
  global:
    proxy:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
