vault:
  server:
    dev:
      enabled: false
    ha:
      enabled: true
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 5
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m
