repoUrl: https://github.com/rohankankapurkar/k8s
targetRevision: HEAD
spec:
  destination:
    server: https://kubernetes.default.svc
applications:
- name: vault
  namespace: vault
  syncWave: '0'
- name: istio
  namespace: istio-system
  syncWave: '1'
  dependencies:
  - vault
- name: prometheus
  namespace: monitoring
  syncWave: '2'
  dependencies:
  - istio
