apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO
    targetRevision: HEAD
    path: infrastructure/root-application
    # Add this section to reference your GitHub credentials secret
    credentials:
      secretName: github-repo-creds
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    timeout: 600s